
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

using MyGeneration.dOOdads;

namespace DAL
{
	public abstract class _EventType : SqlClientEntity
	{
		public _EventType()
		{
			this.QuerySource = "EventType";
			this.MappingName = "EventType";

		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
			
		}
		
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			ListDictionary parameters = null;
			
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_EventTypeLoadAll]", parameters);
		}
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(int EventTypeID)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.EventTypeID, EventTypeID);

		
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_EventTypeLoadByPrimaryKey]", parameters);
		}
		
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter EventTypeID
			{
				get
				{
					return new SqlParameter("@EventTypeID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter EventTypeName
			{
				get
				{
					return new SqlParameter("@EventTypeName", SqlDbType.NVarChar, 500);
				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string EventTypeID = "EventTypeID";
            public const string EventTypeName = "EventTypeName";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[EventTypeID] = _EventType.PropertyNames.EventTypeID;
					ht[EventTypeName] = _EventType.PropertyNames.EventTypeName;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string EventTypeID = "EventTypeID";
            public const string EventTypeName = "EventTypeName";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[EventTypeID] = _EventType.ColumnNames.EventTypeID;
					ht[EventTypeName] = _EventType.ColumnNames.EventTypeName;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string EventTypeID = "s_EventTypeID";
            public const string EventTypeName = "s_EventTypeName";

		}
		#endregion		
		
		#region Properties
	
		public virtual int EventTypeID
	    {
			get
	        {
				return base.Getint(ColumnNames.EventTypeID);
			}
			set
	        {
				base.Setint(ColumnNames.EventTypeID, value);
			}
		}

		public virtual string EventTypeName
	    {
			get
	        {
				return base.Getstring(ColumnNames.EventTypeName);
			}
			set
	        {
				base.Setstring(ColumnNames.EventTypeName, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_EventTypeID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.EventTypeID) ? string.Empty : base.GetintAsString(ColumnNames.EventTypeID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.EventTypeID);
				else
					this.EventTypeID = base.SetintAsString(ColumnNames.EventTypeID, value);
			}
		}

		public virtual string s_EventTypeName
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.EventTypeName) ? string.Empty : base.GetstringAsString(ColumnNames.EventTypeName);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.EventTypeName);
				else
					this.EventTypeName = base.SetstringAsString(ColumnNames.EventTypeName, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter EventTypeID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.EventTypeID, Parameters.EventTypeID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter EventTypeName
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.EventTypeName, Parameters.EventTypeName);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter EventTypeID
		    {
				get
		        {
					if(_EventTypeID_W == null)
	        	    {
						_EventTypeID_W = TearOff.EventTypeID;
					}
					return _EventTypeID_W;
				}
			}

			public WhereParameter EventTypeName
		    {
				get
		        {
					if(_EventTypeName_W == null)
	        	    {
						_EventTypeName_W = TearOff.EventTypeName;
					}
					return _EventTypeName_W;
				}
			}

			private WhereParameter _EventTypeID_W = null;
			private WhereParameter _EventTypeName_W = null;

			public void WhereClauseReset()
			{
				_EventTypeID_W = null;
				_EventTypeName_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter EventTypeID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.EventTypeID, Parameters.EventTypeID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter EventTypeName
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.EventTypeName, Parameters.EventTypeName);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter EventTypeID
		    {
				get
		        {
					if(_EventTypeID_W == null)
	        	    {
						_EventTypeID_W = TearOff.EventTypeID;
					}
					return _EventTypeID_W;
				}
			}

			public AggregateParameter EventTypeName
		    {
				get
		        {
					if(_EventTypeName_W == null)
	        	    {
						_EventTypeName_W = TearOff.EventTypeName;
					}
					return _EventTypeName_W;
				}
			}

			private AggregateParameter _EventTypeID_W = null;
			private AggregateParameter _EventTypeName_W = null;

			public void AggregateClauseReset()
			{
				_EventTypeID_W = null;
				_EventTypeName_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_EventTypeInsert]";
	
			CreateParameters(cmd);
			
			SqlParameter p;
			p = cmd.Parameters[Parameters.EventTypeID.ParameterName];
			p.Direction = ParameterDirection.Output;
    
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_EventTypeUpdate]";
	
			CreateParameters(cmd);
			      
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_EventTypeDelete]";
	
			SqlParameter p;
			p = cmd.Parameters.Add(Parameters.EventTypeID);
			p.SourceColumn = ColumnNames.EventTypeID;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SqlCommand cmd)
		{
			SqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.EventTypeID);
			p.SourceColumn = ColumnNames.EventTypeID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.EventTypeName);
			p.SourceColumn = ColumnNames.EventTypeName;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}
	}
}
