
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

using MyGeneration.dOOdads;

namespace DAL
{
	public abstract class _HomeImageSlider : SqlClientEntity
	{
		public _HomeImageSlider()
		{
			this.QuerySource = "HomeImageSlider";
			this.MappingName = "HomeImageSlider";

		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
			
		}
		
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			ListDictionary parameters = null;
			
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_HomeImageSliderLoadAll]", parameters);
		}
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(int HomeImageSliderID)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.HomeImageSliderID, HomeImageSliderID);

		
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_HomeImageSliderLoadByPrimaryKey]", parameters);
		}
		
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter HomeImageSliderID
			{
				get
				{
					return new SqlParameter("@HomeImageSliderID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter ImagePath
			{
				get
				{
					return new SqlParameter("@ImagePath", SqlDbType.NVarChar, 500);
				}
			}
			
			public static SqlParameter ImageTitle
			{
				get
				{
					return new SqlParameter("@ImageTitle", SqlDbType.NVarChar, 500);
				}
			}
			
			public static SqlParameter ImageDescription
			{
				get
				{
					return new SqlParameter("@ImageDescription", SqlDbType.NVarChar, 500);
				}
			}
			
			public static SqlParameter ImageLink
			{
				get
				{
					return new SqlParameter("@ImageLink", SqlDbType.NVarChar, 500);
				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string HomeImageSliderID = "HomeImageSliderID";
            public const string ImagePath = "ImagePath";
            public const string ImageTitle = "ImageTitle";
            public const string ImageDescription = "ImageDescription";
            public const string ImageLink = "ImageLink";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[HomeImageSliderID] = _HomeImageSlider.PropertyNames.HomeImageSliderID;
					ht[ImagePath] = _HomeImageSlider.PropertyNames.ImagePath;
					ht[ImageTitle] = _HomeImageSlider.PropertyNames.ImageTitle;
					ht[ImageDescription] = _HomeImageSlider.PropertyNames.ImageDescription;
					ht[ImageLink] = _HomeImageSlider.PropertyNames.ImageLink;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string HomeImageSliderID = "HomeImageSliderID";
            public const string ImagePath = "ImagePath";
            public const string ImageTitle = "ImageTitle";
            public const string ImageDescription = "ImageDescription";
            public const string ImageLink = "ImageLink";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[HomeImageSliderID] = _HomeImageSlider.ColumnNames.HomeImageSliderID;
					ht[ImagePath] = _HomeImageSlider.ColumnNames.ImagePath;
					ht[ImageTitle] = _HomeImageSlider.ColumnNames.ImageTitle;
					ht[ImageDescription] = _HomeImageSlider.ColumnNames.ImageDescription;
					ht[ImageLink] = _HomeImageSlider.ColumnNames.ImageLink;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string HomeImageSliderID = "s_HomeImageSliderID";
            public const string ImagePath = "s_ImagePath";
            public const string ImageTitle = "s_ImageTitle";
            public const string ImageDescription = "s_ImageDescription";
            public const string ImageLink = "s_ImageLink";

		}
		#endregion		
		
		#region Properties
	
		public virtual int HomeImageSliderID
	    {
			get
	        {
				return base.Getint(ColumnNames.HomeImageSliderID);
			}
			set
	        {
				base.Setint(ColumnNames.HomeImageSliderID, value);
			}
		}

		public virtual string ImagePath
	    {
			get
	        {
				return base.Getstring(ColumnNames.ImagePath);
			}
			set
	        {
				base.Setstring(ColumnNames.ImagePath, value);
			}
		}

		public virtual string ImageTitle
	    {
			get
	        {
				return base.Getstring(ColumnNames.ImageTitle);
			}
			set
	        {
				base.Setstring(ColumnNames.ImageTitle, value);
			}
		}

		public virtual string ImageDescription
	    {
			get
	        {
				return base.Getstring(ColumnNames.ImageDescription);
			}
			set
	        {
				base.Setstring(ColumnNames.ImageDescription, value);
			}
		}

		public virtual string ImageLink
	    {
			get
	        {
				return base.Getstring(ColumnNames.ImageLink);
			}
			set
	        {
				base.Setstring(ColumnNames.ImageLink, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_HomeImageSliderID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.HomeImageSliderID) ? string.Empty : base.GetintAsString(ColumnNames.HomeImageSliderID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.HomeImageSliderID);
				else
					this.HomeImageSliderID = base.SetintAsString(ColumnNames.HomeImageSliderID, value);
			}
		}

		public virtual string s_ImagePath
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.ImagePath) ? string.Empty : base.GetstringAsString(ColumnNames.ImagePath);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.ImagePath);
				else
					this.ImagePath = base.SetstringAsString(ColumnNames.ImagePath, value);
			}
		}

		public virtual string s_ImageTitle
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.ImageTitle) ? string.Empty : base.GetstringAsString(ColumnNames.ImageTitle);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.ImageTitle);
				else
					this.ImageTitle = base.SetstringAsString(ColumnNames.ImageTitle, value);
			}
		}

		public virtual string s_ImageDescription
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.ImageDescription) ? string.Empty : base.GetstringAsString(ColumnNames.ImageDescription);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.ImageDescription);
				else
					this.ImageDescription = base.SetstringAsString(ColumnNames.ImageDescription, value);
			}
		}

		public virtual string s_ImageLink
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.ImageLink) ? string.Empty : base.GetstringAsString(ColumnNames.ImageLink);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.ImageLink);
				else
					this.ImageLink = base.SetstringAsString(ColumnNames.ImageLink, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter HomeImageSliderID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.HomeImageSliderID, Parameters.HomeImageSliderID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter ImagePath
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.ImagePath, Parameters.ImagePath);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter ImageTitle
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.ImageTitle, Parameters.ImageTitle);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter ImageDescription
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.ImageDescription, Parameters.ImageDescription);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter ImageLink
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.ImageLink, Parameters.ImageLink);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter HomeImageSliderID
		    {
				get
		        {
					if(_HomeImageSliderID_W == null)
	        	    {
						_HomeImageSliderID_W = TearOff.HomeImageSliderID;
					}
					return _HomeImageSliderID_W;
				}
			}

			public WhereParameter ImagePath
		    {
				get
		        {
					if(_ImagePath_W == null)
	        	    {
						_ImagePath_W = TearOff.ImagePath;
					}
					return _ImagePath_W;
				}
			}

			public WhereParameter ImageTitle
		    {
				get
		        {
					if(_ImageTitle_W == null)
	        	    {
						_ImageTitle_W = TearOff.ImageTitle;
					}
					return _ImageTitle_W;
				}
			}

			public WhereParameter ImageDescription
		    {
				get
		        {
					if(_ImageDescription_W == null)
	        	    {
						_ImageDescription_W = TearOff.ImageDescription;
					}
					return _ImageDescription_W;
				}
			}

			public WhereParameter ImageLink
		    {
				get
		        {
					if(_ImageLink_W == null)
	        	    {
						_ImageLink_W = TearOff.ImageLink;
					}
					return _ImageLink_W;
				}
			}

			private WhereParameter _HomeImageSliderID_W = null;
			private WhereParameter _ImagePath_W = null;
			private WhereParameter _ImageTitle_W = null;
			private WhereParameter _ImageDescription_W = null;
			private WhereParameter _ImageLink_W = null;

			public void WhereClauseReset()
			{
				_HomeImageSliderID_W = null;
				_ImagePath_W = null;
				_ImageTitle_W = null;
				_ImageDescription_W = null;
				_ImageLink_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter HomeImageSliderID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.HomeImageSliderID, Parameters.HomeImageSliderID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter ImagePath
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.ImagePath, Parameters.ImagePath);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter ImageTitle
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.ImageTitle, Parameters.ImageTitle);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter ImageDescription
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.ImageDescription, Parameters.ImageDescription);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter ImageLink
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.ImageLink, Parameters.ImageLink);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter HomeImageSliderID
		    {
				get
		        {
					if(_HomeImageSliderID_W == null)
	        	    {
						_HomeImageSliderID_W = TearOff.HomeImageSliderID;
					}
					return _HomeImageSliderID_W;
				}
			}

			public AggregateParameter ImagePath
		    {
				get
		        {
					if(_ImagePath_W == null)
	        	    {
						_ImagePath_W = TearOff.ImagePath;
					}
					return _ImagePath_W;
				}
			}

			public AggregateParameter ImageTitle
		    {
				get
		        {
					if(_ImageTitle_W == null)
	        	    {
						_ImageTitle_W = TearOff.ImageTitle;
					}
					return _ImageTitle_W;
				}
			}

			public AggregateParameter ImageDescription
		    {
				get
		        {
					if(_ImageDescription_W == null)
	        	    {
						_ImageDescription_W = TearOff.ImageDescription;
					}
					return _ImageDescription_W;
				}
			}

			public AggregateParameter ImageLink
		    {
				get
		        {
					if(_ImageLink_W == null)
	        	    {
						_ImageLink_W = TearOff.ImageLink;
					}
					return _ImageLink_W;
				}
			}

			private AggregateParameter _HomeImageSliderID_W = null;
			private AggregateParameter _ImagePath_W = null;
			private AggregateParameter _ImageTitle_W = null;
			private AggregateParameter _ImageDescription_W = null;
			private AggregateParameter _ImageLink_W = null;

			public void AggregateClauseReset()
			{
				_HomeImageSliderID_W = null;
				_ImagePath_W = null;
				_ImageTitle_W = null;
				_ImageDescription_W = null;
				_ImageLink_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_HomeImageSliderInsert]";
	
			CreateParameters(cmd);
			
			SqlParameter p;
			p = cmd.Parameters[Parameters.HomeImageSliderID.ParameterName];
			p.Direction = ParameterDirection.Output;
    
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_HomeImageSliderUpdate]";
	
			CreateParameters(cmd);
			      
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_HomeImageSliderDelete]";
	
			SqlParameter p;
			p = cmd.Parameters.Add(Parameters.HomeImageSliderID);
			p.SourceColumn = ColumnNames.HomeImageSliderID;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SqlCommand cmd)
		{
			SqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.HomeImageSliderID);
			p.SourceColumn = ColumnNames.HomeImageSliderID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.ImagePath);
			p.SourceColumn = ColumnNames.ImagePath;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.ImageTitle);
			p.SourceColumn = ColumnNames.ImageTitle;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.ImageDescription);
			p.SourceColumn = ColumnNames.ImageDescription;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.ImageLink);
			p.SourceColumn = ColumnNames.ImageLink;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}
	}
}
