
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

using MyGeneration.dOOdads;

namespace DAL
{
	public abstract class _Tasks : SqlClientEntity
	{
		public _Tasks()
		{
			this.QuerySource = "Tasks";
			this.MappingName = "Tasks";

		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
			
		}
		
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			ListDictionary parameters = null;
			
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_TasksLoadAll]", parameters);
		}
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(int TaskID)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.TaskID, TaskID);

		
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_TasksLoadByPrimaryKey]", parameters);
		}
		
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter TaskID
			{
				get
				{
					return new SqlParameter("@TaskID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter MemberID
			{
				get
				{
					return new SqlParameter("@MemberID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter TaskName
			{
				get
				{
					return new SqlParameter("@TaskName", SqlDbType.NVarChar, 500);
				}
			}
			
			public static SqlParameter TaskResult
			{
				get
				{
					return new SqlParameter("@TaskResult", SqlDbType.NVarChar, 50);
				}
			}
			
			public static SqlParameter Notes
			{
				get
				{
					return new SqlParameter("@Notes", SqlDbType.NVarChar, 500);
				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string TaskID = "TaskID";
            public const string MemberID = "MemberID";
            public const string TaskName = "TaskName";
            public const string TaskResult = "TaskResult";
            public const string Notes = "Notes";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[TaskID] = _Tasks.PropertyNames.TaskID;
					ht[MemberID] = _Tasks.PropertyNames.MemberID;
					ht[TaskName] = _Tasks.PropertyNames.TaskName;
					ht[TaskResult] = _Tasks.PropertyNames.TaskResult;
					ht[Notes] = _Tasks.PropertyNames.Notes;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string TaskID = "TaskID";
            public const string MemberID = "MemberID";
            public const string TaskName = "TaskName";
            public const string TaskResult = "TaskResult";
            public const string Notes = "Notes";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[TaskID] = _Tasks.ColumnNames.TaskID;
					ht[MemberID] = _Tasks.ColumnNames.MemberID;
					ht[TaskName] = _Tasks.ColumnNames.TaskName;
					ht[TaskResult] = _Tasks.ColumnNames.TaskResult;
					ht[Notes] = _Tasks.ColumnNames.Notes;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string TaskID = "s_TaskID";
            public const string MemberID = "s_MemberID";
            public const string TaskName = "s_TaskName";
            public const string TaskResult = "s_TaskResult";
            public const string Notes = "s_Notes";

		}
		#endregion		
		
		#region Properties
	
		public virtual int TaskID
	    {
			get
	        {
				return base.Getint(ColumnNames.TaskID);
			}
			set
	        {
				base.Setint(ColumnNames.TaskID, value);
			}
		}

		public virtual int MemberID
	    {
			get
	        {
				return base.Getint(ColumnNames.MemberID);
			}
			set
	        {
				base.Setint(ColumnNames.MemberID, value);
			}
		}

		public virtual string TaskName
	    {
			get
	        {
				return base.Getstring(ColumnNames.TaskName);
			}
			set
	        {
				base.Setstring(ColumnNames.TaskName, value);
			}
		}

		public virtual string TaskResult
	    {
			get
	        {
				return base.Getstring(ColumnNames.TaskResult);
			}
			set
	        {
				base.Setstring(ColumnNames.TaskResult, value);
			}
		}

		public virtual string Notes
	    {
			get
	        {
				return base.Getstring(ColumnNames.Notes);
			}
			set
	        {
				base.Setstring(ColumnNames.Notes, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_TaskID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.TaskID) ? string.Empty : base.GetintAsString(ColumnNames.TaskID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.TaskID);
				else
					this.TaskID = base.SetintAsString(ColumnNames.TaskID, value);
			}
		}

		public virtual string s_MemberID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.MemberID) ? string.Empty : base.GetintAsString(ColumnNames.MemberID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.MemberID);
				else
					this.MemberID = base.SetintAsString(ColumnNames.MemberID, value);
			}
		}

		public virtual string s_TaskName
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.TaskName) ? string.Empty : base.GetstringAsString(ColumnNames.TaskName);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.TaskName);
				else
					this.TaskName = base.SetstringAsString(ColumnNames.TaskName, value);
			}
		}

		public virtual string s_TaskResult
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.TaskResult) ? string.Empty : base.GetstringAsString(ColumnNames.TaskResult);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.TaskResult);
				else
					this.TaskResult = base.SetstringAsString(ColumnNames.TaskResult, value);
			}
		}

		public virtual string s_Notes
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Notes) ? string.Empty : base.GetstringAsString(ColumnNames.Notes);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Notes);
				else
					this.Notes = base.SetstringAsString(ColumnNames.Notes, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter TaskID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.TaskID, Parameters.TaskID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter MemberID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.MemberID, Parameters.MemberID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter TaskName
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.TaskName, Parameters.TaskName);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter TaskResult
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.TaskResult, Parameters.TaskResult);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Notes
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Notes, Parameters.Notes);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter TaskID
		    {
				get
		        {
					if(_TaskID_W == null)
	        	    {
						_TaskID_W = TearOff.TaskID;
					}
					return _TaskID_W;
				}
			}

			public WhereParameter MemberID
		    {
				get
		        {
					if(_MemberID_W == null)
	        	    {
						_MemberID_W = TearOff.MemberID;
					}
					return _MemberID_W;
				}
			}

			public WhereParameter TaskName
		    {
				get
		        {
					if(_TaskName_W == null)
	        	    {
						_TaskName_W = TearOff.TaskName;
					}
					return _TaskName_W;
				}
			}

			public WhereParameter TaskResult
		    {
				get
		        {
					if(_TaskResult_W == null)
	        	    {
						_TaskResult_W = TearOff.TaskResult;
					}
					return _TaskResult_W;
				}
			}

			public WhereParameter Notes
		    {
				get
		        {
					if(_Notes_W == null)
	        	    {
						_Notes_W = TearOff.Notes;
					}
					return _Notes_W;
				}
			}

			private WhereParameter _TaskID_W = null;
			private WhereParameter _MemberID_W = null;
			private WhereParameter _TaskName_W = null;
			private WhereParameter _TaskResult_W = null;
			private WhereParameter _Notes_W = null;

			public void WhereClauseReset()
			{
				_TaskID_W = null;
				_MemberID_W = null;
				_TaskName_W = null;
				_TaskResult_W = null;
				_Notes_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter TaskID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.TaskID, Parameters.TaskID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter MemberID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.MemberID, Parameters.MemberID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter TaskName
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.TaskName, Parameters.TaskName);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter TaskResult
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.TaskResult, Parameters.TaskResult);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Notes
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Notes, Parameters.Notes);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter TaskID
		    {
				get
		        {
					if(_TaskID_W == null)
	        	    {
						_TaskID_W = TearOff.TaskID;
					}
					return _TaskID_W;
				}
			}

			public AggregateParameter MemberID
		    {
				get
		        {
					if(_MemberID_W == null)
	        	    {
						_MemberID_W = TearOff.MemberID;
					}
					return _MemberID_W;
				}
			}

			public AggregateParameter TaskName
		    {
				get
		        {
					if(_TaskName_W == null)
	        	    {
						_TaskName_W = TearOff.TaskName;
					}
					return _TaskName_W;
				}
			}

			public AggregateParameter TaskResult
		    {
				get
		        {
					if(_TaskResult_W == null)
	        	    {
						_TaskResult_W = TearOff.TaskResult;
					}
					return _TaskResult_W;
				}
			}

			public AggregateParameter Notes
		    {
				get
		        {
					if(_Notes_W == null)
	        	    {
						_Notes_W = TearOff.Notes;
					}
					return _Notes_W;
				}
			}

			private AggregateParameter _TaskID_W = null;
			private AggregateParameter _MemberID_W = null;
			private AggregateParameter _TaskName_W = null;
			private AggregateParameter _TaskResult_W = null;
			private AggregateParameter _Notes_W = null;

			public void AggregateClauseReset()
			{
				_TaskID_W = null;
				_MemberID_W = null;
				_TaskName_W = null;
				_TaskResult_W = null;
				_Notes_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_TasksInsert]";
	
			CreateParameters(cmd);
			
			SqlParameter p;
			p = cmd.Parameters[Parameters.TaskID.ParameterName];
			p.Direction = ParameterDirection.Output;
    
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_TasksUpdate]";
	
			CreateParameters(cmd);
			      
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_TasksDelete]";
	
			SqlParameter p;
			p = cmd.Parameters.Add(Parameters.TaskID);
			p.SourceColumn = ColumnNames.TaskID;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SqlCommand cmd)
		{
			SqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.TaskID);
			p.SourceColumn = ColumnNames.TaskID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.MemberID);
			p.SourceColumn = ColumnNames.MemberID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.TaskName);
			p.SourceColumn = ColumnNames.TaskName;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.TaskResult);
			p.SourceColumn = ColumnNames.TaskResult;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Notes);
			p.SourceColumn = ColumnNames.Notes;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}
	}
}
